"""Draw history users

Revision ID: e04316ed7aa5
Revises: 8cede0520b3c
Create Date: 2025-05-18 17:46:33.455530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04316ed7aa5'
down_revision: Union[str, None] = '8cede0520b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draw_history', sa.Column('user', sa.String(), server_default='Unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draw_history', 'user')
    # ### end Alembic commands ###
